import { Vehicle, Task, CustomerLocation, Region, Priority, TaskStatus } from '../types';

export const INITIAL_CUSTOMERS: CustomerLocation[] = [
  {
    id: 'cust-1',
    name: 'Baku Medical Center',
    address: 'Babək pr. 11A, Xətai',
    region: 'Xətai',
    lat: 40.3831,
    lng: 49.8824,
    contactPerson: 'Dr. Əli Kərimov',
    phone: '+994 12 404 0303',
    category: 'Hospital',
  },
  {
    id: 'cust-2',
    name: 'Port Baku Towers',
    address: 'Neftçilər pr. 153, Səbail',
    region: 'Səbail',
    lat: 40.3738,
    lng: 49.8552,
    contactPerson: 'Nərgiz Məmmədova',
    phone: '+994 12 599 0000',
    category: 'Commercial',
  },
  {
    id: 'cust-3',
    name: 'SOCAR Tower HQ',
    address: 'Heydər Əliyev pr. 121, Nərimanov',
    region: 'Nərimanov',
    lat: 40.4042,
    lng: 49.8973,
    contactPerson: 'Rəşad Qasımov',
    phone: '+994 12 521 0000',
    category: 'Commercial',
  },
  {
    id: 'cust-4',
    name: 'Gənclik Mall Logistics',
    address: 'Fətəli Xan Xoyski pr. 14, Nərimanov',
    region: 'Nərimanov',
    lat: 40.4002,
    lng: 49.8519,
    contactPerson: 'Samirə Həsənova',
    phone: '+994 12 499 8700',
    category: 'Commercial',
  },
  {
    id: 'cust-5',
    name: 'Yasamal Innovation Hub',
    address: 'Zahid Xəlilov küç. 23, Yasamal',
    region: 'Yasamal',
    lat: 40.3756,
    lng: 49.8152,
    contactPerson: 'Orxan Əliyev',
    phone: '+994 50 222 3411',
    category: 'Commercial',
  },
  {
    id: 'cust-6',
    name: 'Bravo Hypermarket Koroğlu',
    address: 'Heydər Əliyev pr. 172, Nərimanov',
    region: 'Nərimanov',
    lat: 40.4208,
    lng: 49.9189,
    contactPerson: 'Elmir Babayev',
    phone: '+994 12 404 1122',
    category: 'Commercial',
  },
  {
    id: 'cust-7',
    name: 'Nəsimi Rayon Mərkəzi Xəstəxanası',
    address: 'Səməd Vurğun küç. 98, Nəsimi',
    region: 'Nəsimi',
    lat: 40.3951,
    lng: 49.8367,
    contactPerson: 'Dr. Sevda Quliyeva',
    phone: '+994 12 440 2314',
    category: 'Hospital',
  },
  {
    id: 'cust-8',
    name: 'Binəqədi Sənaye Zonası',
    address: 'Baksol yolu 4, Binəqədi',
    region: 'Binəqədi',
    lat: 40.4325,
    lng: 49.8631,
    contactPerson: 'İlqar Məcidov',
    phone: '+994 55 400 9012',
    category: 'Industrial',
  },
  {
    id: 'cust-9',
    name: 'Caspian Waterfront Mall',
    address: 'Dənizkənarı Milli Park, Səbail',
    region: 'Səbail',
    lat: 40.3621,
    lng: 49.8402,
    contactPerson: 'Fərid Tağıyev',
    phone: '+994 12 505 5500',
    category: 'Commercial',
  },
  {
    id: 'cust-10',
    name: 'Gəncə Regional Logistika Terminalı',
    address: 'Heydər Əliyev pr. 84, Gəncə',
    region: 'Gəncə',
    lat: 40.6828,
    lng: 46.3606,
    contactPerson: 'Anar Qurbanov',
    phone: '+994 22 256 7010',
    category: 'Industrial',
  }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'v-101',
    plate: '10-AA-101',
    driverName: 'Elvin Məmmədov',
    driverPhone: '+994 50 311 4455',
    status: 'BUSY',
    speed: 42,
    battery: 78,
    fuelLevel: 82,
    heading: 85,
    location: { lat: 40.3854, lng: 49.8672 },
    gpsAccuracy: 8,
    lastUpdate: '8 sec ago',
    currentTaskId: 'TSK-4821',
    currentTaskTitle: 'Express Medical Supply Delivery',
    assignedRegion: 'Nəsimi',
    model: 'Mercedes-Benz Sprinter 316',
    etaMinutes: 12,
  },
  {
    id: 'v-245',
    plate: '10-BB-245',
    driverName: 'Murad Əliyev',
    driverPhone: '+994 55 422 9988',
    status: 'ONLINE',
    speed: 36,
    battery: 92,
    fuelLevel: 68,
    heading: 140,
    location: { lat: 40.3721, lng: 49.8441 },
    gpsAccuracy: 6,
    lastUpdate: '3 sec ago',
    currentTaskId: 'TSK-4822',
    currentTaskTitle: 'Corporate IT Server Transport',
    assignedRegion: 'Səbail',
    model: 'Ford Transit Custom',
    etaMinutes: 18,
  },
  {
    id: 'v-782',
    plate: '99-XY-782',
    driverName: 'Tural Hüseynov',
    driverPhone: '+994 70 811 2030',
    status: 'IDLE',
    speed: 0,
    battery: 88,
    fuelLevel: 90,
    heading: 0,
    location: { lat: 40.4011, lng: 49.8525 },
    gpsAccuracy: 5,
    lastUpdate: '15 sec ago',
    assignedRegion: 'Nərimanov',
    model: 'Volkswagen Crafter TDI',
    etaMinutes: 0,
  },
  {
    id: 'v-314',
    plate: '90-KK-314',
    driverName: 'Kamran Quliyev',
    driverPhone: '+994 51 909 3322',
    status: 'WARNING',
    speed: 18,
    battery: 24,
    fuelLevel: 15,
    heading: 260,
    location: { lat: 40.3792, lng: 49.8118 },
    gpsAccuracy: 12,
    lastUpdate: '22 sec ago',
    currentTaskId: 'TSK-4824',
    currentTaskTitle: 'Cold Chain Vaccine Batch #88',
    assignedRegion: 'Yasamal',
    model: 'Renault Master Z.E.',
    etaMinutes: 9,
  },
  {
    id: 'v-501',
    plate: '77-ZZ-501',
    driverName: 'Rauf İbrahimov',
    driverPhone: '+994 50 633 1199',
    status: 'BUSY',
    speed: 55,
    battery: 65,
    fuelLevel: 55,
    heading: 320,
    location: { lat: 40.4284, lng: 49.8711 },
    gpsAccuracy: 7,
    lastUpdate: '5 sec ago',
    currentTaskId: 'TSK-4825',
    currentTaskTitle: 'Industrial Parts Urgent Dispatch',
    assignedRegion: 'Binəqədi',
    model: 'Iveco Daily 35S',
    etaMinutes: 24,
  },
  {
    id: 'v-888',
    plate: '10-TF-888',
    driverName: 'Leyla Bağırova',
    driverPhone: '+994 55 771 8844',
    status: 'ONLINE',
    speed: 28,
    battery: 95,
    fuelLevel: 75,
    heading: 195,
    location: { lat: 40.3812, lng: 49.8920 },
    gpsAccuracy: 6,
    lastUpdate: '4 sec ago',
    currentTaskId: 'TSK-4826',
    currentTaskTitle: 'Hospital Diagnostic Specimens',
    assignedRegion: 'Xətai',
    model: 'Toyota Proace EV',
    etaMinutes: 14,
  },
  {
    id: 'v-420',
    plate: '99-NN-420',
    driverName: 'Nurlan Qasımov',
    driverPhone: '+994 77 344 5511',
    status: 'BUSY',
    speed: 48,
    battery: 84,
    fuelLevel: 80,
    heading: 110,
    location: { lat: 40.3945, lng: 49.8312 },
    gpsAccuracy: 5,
    lastUpdate: '7 sec ago',
    currentTaskId: 'TSK-4827',
    currentTaskTitle: 'Urgent Document Courier Service',
    assignedRegion: 'Nəsimi',
    model: 'Peugeot Partner',
    etaMinutes: 11,
  },
  {
    id: 'v-909',
    plate: '10-OK-909',
    driverName: 'Vüsal Əhmədov',
    driverPhone: '+994 50 999 1234',
    status: 'OFFLINE',
    speed: 0,
    battery: 12,
    fuelLevel: 40,
    heading: 0,
    location: { lat: 40.3688, lng: 49.8290 },
    gpsAccuracy: 25,
    lastUpdate: '18 min ago',
    assignedRegion: 'Yasamal',
    model: 'Ford Transit EcoBlue',
    etaMinutes: 0,
  },
  {
    id: 'v-112',
    plate: '90-DH-112',
    driverName: 'Fuad Rəhimov',
    driverPhone: '+994 55 512 8765',
    status: 'ONLINE',
    speed: 34,
    battery: 70,
    fuelLevel: 62,
    heading: 45,
    location: { lat: 40.4120, lng: 49.8860 },
    gpsAccuracy: 7,
    lastUpdate: '6 sec ago',
    currentTaskId: 'TSK-4829',
    currentTaskTitle: 'Commercial Supermarket Restock',
    assignedRegion: 'Nərimanov',
    model: 'Mercedes-Benz Vito 114',
    etaMinutes: 21,
  },
  {
    id: 'v-777',
    plate: '10-AZ-777',
    driverName: 'Samir Novruzov',
    driverPhone: '+994 51 230 4567',
    status: 'ONLINE',
    speed: 51,
    battery: 81,
    fuelLevel: 71,
    heading: 275,
    location: { lat: 40.6865, lng: 46.3680 },
    gpsAccuracy: 6,
    lastUpdate: '2 sec ago',
    currentTaskId: 'TSK-4830',
    currentTaskTitle: 'Ganja Intercity Medical Transport',
    assignedRegion: 'Gəncə',
    model: 'Hyundai H350 Cargo',
    etaMinutes: 35,
  }
];

// Generate 75 realistic tasks across regions and statuses
export function generateInitialTasks(): Task[] {
  const regions: Region[] = ['Baku', 'Yasamal', 'Nəsimi', 'Nərimanov', 'Binəqədi', 'Xətai', 'Səbail', 'Gəncə'];
  const priorities: Priority[] = ['Low', 'Medium', 'High', 'Critical'];
  const statuses: TaskStatus[] = ['Pending', 'Assigned', 'In Progress', 'Completed', 'Cancelled'];
  const types: Task['type'][] = ['Delivery', 'Emergency', 'Inspection', 'Service', 'Supply'];

  const customerPool = [
    { name: 'Baku Medical Center', addr: 'Babək pr. 11A, Xətai', phone: '+994 12 404 0303', region: 'Xətai' as Region, lat: 40.3831, lng: 49.8824 },
    { name: 'Port Baku Towers', addr: 'Neftçilər pr. 153, Səbail', phone: '+994 12 599 0000', region: 'Səbail' as Region, lat: 40.3738, lng: 49.8552 },
    { name: 'SOCAR Tower HQ', addr: 'Heydər Əliyev pr. 121, Nərimanov', phone: '+994 12 521 0000', region: 'Nərimanov' as Region, lat: 40.4042, lng: 49.8973 },
    { name: 'Gənclik Mall Logistics', addr: 'Fətəli Xan Xoyski pr. 14', phone: '+994 12 499 8700', region: 'Nərimanov' as Region, lat: 40.4002, lng: 49.8519 },
    { name: 'Yasamal Tech Park', addr: 'Zahid Xəlilov küç. 23', phone: '+994 50 222 3411', region: 'Yasamal' as Region, lat: 40.3756, lng: 49.8152 },
    { name: 'Bravo Hypermarket Koroğlu', addr: 'Heydər Əliyev pr. 172', phone: '+994 12 404 1122', region: 'Nərimanov' as Region, lat: 40.4208, lng: 49.9189 },
    { name: 'Nəsimi Health Hub', addr: 'Səməd Vurğun küç. 98', phone: '+994 12 440 2314', region: 'Nəsimi' as Region, lat: 40.3951, lng: 49.8367 },
    { name: 'Binəqədi Logistics Base', addr: 'Baksol yolu 4', phone: '+994 55 400 9012', region: 'Binəqədi' as Region, lat: 40.4325, lng: 49.8631 },
    { name: 'Caspian Coastline Facilities', addr: 'Dənizkənarı Bulvar', phone: '+994 12 505 5500', region: 'Səbail' as Region, lat: 40.3621, lng: 49.8402 },
    { name: 'Gəncə Regional Depot', addr: 'Heydər Əliyev pr. 84, Gəncə', phone: '+994 22 256 7010', region: 'Gəncə' as Region, lat: 40.6828, lng: 46.3606 }
  ];

  const driversPool = [
    { name: 'Elvin Məmmədov', vehicle: '10-AA-101' },
    { name: 'Murad Əliyev', vehicle: '10-BB-245' },
    { name: 'Tural Hüseynov', vehicle: '99-XY-782' },
    { name: 'Kamran Quliyev', vehicle: '90-KK-314' },
    { name: 'Rauf İbrahimov', vehicle: '77-ZZ-501' },
    { name: 'Leyla Bağırova', vehicle: '10-TF-888' },
    { name: 'Nurlan Qasımov', vehicle: '99-NN-420' },
    { name: 'Fuad Rəhimov', vehicle: '90-DH-112' },
    { name: 'Samir Novruzov', vehicle: '10-AZ-777' },
  ];

  const tasks: Task[] = [];

  for (let i = 1; i <= 75; i++) {
    const cust = customerPool[i % customerPool.length];
    const driver = driversPool[i % driversPool.length];
    const prio = i % 5 === 0 ? 'Critical' : i % 3 === 0 ? 'High' : i % 2 === 0 ? 'Medium' : 'Low';
    const status: TaskStatus = i < 15 ? 'In Progress' : i < 30 ? 'Assigned' : i < 45 ? 'Pending' : i < 68 ? 'Completed' : 'Cancelled';
    const type = types[i % types.length];
    const codeNum = 4800 + i;

    tasks.push({
      id: `task-${i}`,
      code: `TSK-${codeNum}`,
      title: `${type}: ${cust.name} Priority Batch #${i}`,
      customerName: cust.name,
      customerPhone: cust.phone,
      address: cust.addr,
      region: cust.region,
      location: {
        lat: cust.lat + (Math.sin(i) * 0.008),
        lng: cust.lng + (Math.cos(i) * 0.008),
      },
      driverName: status === 'Pending' ? 'Unassigned' : driver.name,
      vehiclePlate: status === 'Pending' ? '—' : driver.vehicle,
      priority: prio,
      status: status,
      createdAt: `2026-09-30 0${8 + (i % 6)}:${(10 + (i * 7) % 50).toString().padStart(2, '0')}`,
      eta: status === 'Completed' ? 'Delivered' : `${10 + (i % 45)} min`,
      type: type,
      notes: `Dispatch order #${codeNum} verified via central NEXUS routing. Handle with care.`,
      barcode: `869000${codeNum}${i % 9}`,
    });
  }

  return tasks;
}

export const INITIAL_ACTIVITY_LOGS = [
  {
    id: 'act-1',
    timestamp: '11:42:08',
    vehiclePlate: '10-AA-101',
    driverName: 'Elvin Məmmədov',
    message: 'Speed alert: 42 km/h entering Heydər Əliyev pr. corridor',
    type: 'info' as const,
  },
  {
    id: 'act-2',
    timestamp: '11:41:40',
    vehiclePlate: '90-KK-314',
    driverName: 'Kamran Quliyev',
    message: 'Low battery threshold reached (24%) in Yasamal area',
    type: 'warning' as const,
  },
  {
    id: 'act-3',
    timestamp: '11:40:15',
    vehiclePlate: '10-BB-245',
    driverName: 'Murad Əliyev',
    message: 'Task TSK-4822 marked In-Progress near Port Baku Towers',
    type: 'success' as const,
  },
  {
    id: 'act-4',
    timestamp: '11:38:55',
    vehiclePlate: '10-OK-909',
    driverName: 'Vüsal Əhmədov',
    message: 'GPS telemetry heartbeat missed (Signal Offline)',
    type: 'alert' as const,
  },
  {
    id: 'act-5',
    timestamp: '11:37:12',
    vehiclePlate: '77-ZZ-501',
    driverName: 'Rauf İbrahimov',
    message: 'En route to Binəqədi Industrial Base with urgent supplies',
    type: 'info' as const,
  },
];
